### ISSUE TITLE
Proposal for Creating a Website with Good UI for JavaScript MCQs

### ISSUE THREAD

**Issue by Zeus2480** [bgwebagency/who-wants-to-be-a-javascriptaire#22]
Hi there,

I would like to propose creating a website with a good UI for the MCQs related to JavaScript in this repository. I believe that having a dedicated website will improve the user experience and make it easier for people to test their JavaScript knowledge.

Here's what I plan to include in the website:

A clean and modern UI design that is easy to navigate
Multiple choice questions related to JavaScript with options and video explanations links
A scoring system to keep track of the user's progress

I have the necessary skills and experience to create this website, and I am confident that it will be a valuable addition to the repository.

Please let me know if you approve of this proposal, and if there are any specific requirements or guidelines that I should follow. I look forward to hearing from you soon.

Thank you for your time and consideration.

**Comment by Zeus2480** [comment]
If you approve my request I will start working on the UI of the website and after getting your approval for the UI I will start working on the website

**Comment by kirandash** [comment]
@Zeus2480 That's an amazing idea. It will be an awesome addition to this repository.

Here's my proposed **tech stack** for the project: 

[React](https://reactjs.org/): For the UI
[Remix](https://remix.run/): Framework for the Client/Server/Routing
[TypeScript](https://www.typescriptlang.org/): Typed JavaScript (necessary for any project you plan to maintain)
[XState](https://xstate.js.org/): State machine tool making complex component state management simple
[Prisma](https://www.prisma.io/): Fantastic ORM with stellar migrations and TypeScript client support
[Express](https://expressjs.com/): Node server framework
[Playwright](https://playwright.dev/): E2E testing framework
[Jest](https://jestjs.io/): Unit/Component testing framework
[Testing Library](https://testing-library.com/): Simple utilities for testing DOM-based user interfaces
[MSW](https://mswjs.io/): Fantastic tool for mocking HTTP requests in the browser/node
[Tailwind CSS](https://tailwindcss.com/): Utility classes for consistent/maintainable styling
[Postcss](https://postcss.org/): CSS processor (pretty much just use it for autoprefixer and tailwind)
[Reach UI](https://reach.tech/): A set of accessible UI components every app needs (accordion/tabs/dialog/etc...)
[ESBuild](https://esbuild.github.io/): JavaScript bundler (used by Remix and [mdx-bundler](https://github.com/kentcdodds/mdx-bundler)).
mdx-bundler: Tool for compiling and bundling MDX for my site content (blog posts and some simple pages).
[Octokit](https://github.com/octokit/octokit.js): Library making interacting with the GitHub API easier.
[Framer Motion](https://www.framer.com/motion/): Great React Animation library
[Unified](https://unifiedjs.com/): Markdown/HTML parser/transformer/compiler system.
[Postgres](https://www.postgresql.org/): Battle tested SQL database
[Redis](https://redis.io/): In-memory database–key/value store.

Here are the **services** this site will use:

[Fly.io](https://fly.io/): Hosting platform
[GitHub Actions](https://github.com/features/actions): Hosted CI pipeline service
[Sentry](https://sentry.io/): Error reporting service

**Steps:**
1. UX Design
2. UI Implementation with static QA
3. Make the QA dynamic and read it from README file so that we don't have to maintain the QA on both README file and the website.
4. Integrate authentication and save user data
5. and much more....

It might seem like a lot of task. But I can already see how amazing it will be. 

@Zeus2480 Please let me know if you have any questions or suggestions. Bdw, you can also text me on [discord](https://discord.com/invite/62VR3MMCVm) if you want a faster response.

**Comment by kirandash** [comment]
> If you approve my request I will start working on the UI of the website and after getting your approval for the UI I will start working on the website

Just to be clear, did you mean to create a design for the website? If yes, may I know which tool do you use for creating design

**Comment by kirandash** [comment]
Following are the tasks to be completed under this issue:

- [ ] Create Design with Figma (To be done by @Zeus2480)
- [ ] Build website with vanilla JS (To be done by @Zeus2480)
- [ ] Deploy website live (To be done by @kirandash)

Title: Who wants to be a javascriptaire

**Game Description:**
Who wants to be a javascriptaire Quiz is an online game where players answer multiple-choice questions in order to win points and become a javascriptaire. The game is based on the popular TV show "Who Wants to Be a Millionaire?" and features lifelines that players can use to help them answer difficult questions.

**Gameplay:**

The game consists of multiple-choice questions, each with four possible answers.
Players have three lifelines they can use to help them answer a question:
"50/50": This lifeline eliminates two of the four possible answers, leaving the player with two choices.
"Ask the Audience": This lifeline shows the percentage of players who chose each of the four possible answers, allowing the player to see which answer is most popular among the audience. We can simulate this by always giving higher percentage to the correct answer.
"Phone a Friend": This lifeline allows the player to call a virtual friend who will provide them with advice on the question.

**User Interface:**
The game's user interface consists of a question panel, answer choices panel, a lifeline panel, and a score board.
The question panel displays the current question and its associated points value/score.
The answer choices panel displays the four possible answers to the question.
The lifeline panel displays the three available lifelines and their corresponding icons.
The score board displays the current score out of total score that user can get.
Technical Specifications:

The game is built using HTML, CSS, and JavaScript.
The game is supposed to use questions from the README.md file.
The lifelines and score board are updated dynamically using JavaScript.
The game tracks the player's progress and updates the scores and lifelines accordingly.
The game uses cookies to store the player's progress so that they can resume the game later if they leave the page.

Let me know if you have any questions or need further clarification.

**Comment by Zeus2480** [comment]
Super Excited to work on this amazing project.

**Comment by Ar-Akhil** [comment]
Love to participate in the build. Do reach out if i can help in any possible way.

thank you.

**Comment by kirandash** [comment]
> Love to participate in the build. Do reach out if i can help in any possible way.
> 
> thank you.

Hi @Ar-Akhil This task is already assigned to @Zeus2480 but I do have open issues on different open-source projects of mine. Please feel free to have a look at them. 

If you still can't find anything then feel free to reach me out on [discord](https://discord.com/invite/62VR3MMCVm) and I will be happy to help you out finding some issues per your interest.

Happy Coding!
